### PR TITLE
[#160176077] Update the paas-rds-broker dependency

### PR DESCRIPTION
**Pull request by keymon**
What?
-----

We have changed the paas-rds-broker `awsrds` module in https://github.com/alphagov/paas-rds-broker/pull/87. This module is used by this project and it is good to keep them updated.

Update the paas-rds-broker dependency to include
latest version of the awsrds module.

run: `dep ensure -update github.com/alphagov/paas-rds-broker`

How to review?
--------------

 - Code review
 - Tests should pass

Who?
---
Anyone

### CODE REVIEW

**Comment by alext** [comment]
There's nothing here that explains the Why.  Why do we need to update this?

**Comment by keymon** [comment]
The test passed in our CI: https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-metric-collector/jobs/integration-test/builds/134

But not sure what is going on with travis.

**Comment by keymon** [comment]
The travis test failed due flaky errors in the scheduler tests: 

```
ginkgo -r -nodes 16 -untilItFails pkg/scheduler/
``` 
eventually fails. We should review that. But it is unrelated to this PR.

**Comment by keymon** [comment]
@alext Are you OK to merge it?

**Pull request merged**
